# Generated by Django 5.0.3 on 2024-04-01 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_city_record_check_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='created_at',
        ),
    ]
